### ISSUE TITLE
Additional Rankings Data Missing

### ISSUE THREAD

**Issue by Techno11** [techguy9984/TBA-API#12]
![image](https://cloud.githubusercontent.com/assets/15097541/23591746/5efcdbb6-01c3-11e7-8991-48892a8db1cf.png)

When making a Rankings Request from the blue alliance, it return more data than last year, causing many things to become out of order, and therfore not returning what need to be returned.

Ex:
`team.played`
Will return the Record(W-L-T)

Please refer to the Table I create above for more info.

**Comment by widavies** [comment]
Alright thanks. I'm not directly involved with a robotics team so thanks
for the help. I'll have the update up soon.

**Comment by Techno11** [comment]
Yeah, no problem.  Glad to be able to contribute to your API

**Comment by Techno11** [comment]
I have made the required changes, and will be creating a pull request after they are tested.

**Comment by widavies** [comment]
Your pull request is available in the latest build: https://github.com/techguy9984/TBA-API/releases/tag/6
