### ISSUE TITLE
Parsing Matches in wrong order?

### ISSUE THREAD

**Issue by Techno11** [techguy9984/TBA-API#14]
I, again, may be doing something wrong, but I have a for loop running, and if the match contains my team number, it collects all the data from the match. All is well with that.  However, when I go to list the matches, it orders them like so:
Q12
Q26
Q47
Q69
**Q7**
Q76

Qualifier 7 should be at the beginning, not between 69 and 70.

**Comment by techguy9984** [comment]
Currently, matches aren't loaded in order. Would you like me to add that functionality?

**Comment by widavies** [comment]
Thanks for the feedback. Just added match sorting by number. Check out this release: https://github.com/techguy9984/TBA-API/releases/tag/6

**Comment by Techno11** [comment]
Great. This works Perfect.  However, now the matches are returned in the wrong order, in the fact that it return the highest match first, and counts down from there. Maybe make this a toggleable feature? Order matches From High-low or Low-High.

It should return The Qualification matches starting with match 1 through whatever, and then Octofinal 1-** Quarterfinal 1-**...Etc.

Thanks!

**Comment by widavies** [comment]
I'll fix it

**Comment by widavies** [comment]
Hey @Techno11 @MLavrentyev @JDaniel29, just letting you know, there is now a V3 api for TBA: https://github.com/wdavies973/TBA-API-V3

**Comment by Techno11** [comment]
Thanks!
