### ISSUE TITLE
getTeamEvents doesn't exist

### ISSUE THREAD

**Issue by JDaniel41** [techguy9984/TBA-API#4]
So, I am using the latest release of TBA-API. After I've done the initial setup, I try to call:
```java
tba.getTeamEvents(4468, 2016);
```
It states that the method doesn't exist in the tba object. I've looked in the Github code and am sure that I am calling it correctly, so what is wrong with my code?

**Comment by widavies** [comment]
I'll get back to you soon

**Comment by widavies** [comment]
Which class is this issue occuring in that you saw the code for ?

**Comment by JDaniel41** [comment]
So, the method is in the [main TBA](https://github.com/techguy9984/TBA-API/blob/master/TBA-API/src/com/cpjd/main/TBA.java) class. I am running the code from a Java compiler and can run every other method (that I've tried).

**Comment by widavies** [comment]
Okay - a fix should be up tonight

**Comment by JDaniel41** [comment]
OK, thanks!

**Comment by widavies** [comment]
Okay - so do you have the latest github code downloaded or are you pulling stuff from the .jar release?

**Comment by JDaniel41** [comment]
I have been pulling stuff from the .jar release

**Comment by Techno11** [comment]
The most recent release (based off of commit 3905a70) does not include that.  The pull request that added that functionality was made after release 3.0 (Commit 3905a70)

**Comment by widavies** [comment]
Okay - The repository had some issues after multiple pull request. It should be fixed now and methods should be working. The current repository has been updated and a new release has been posted at: https://github.com/techguy9984/TBA-API/releases/tag/4.

**Comment by widavies** [comment]
Hey JDaniel, just wanted to let you know that I majorly changed the entire API. It now contains EVERY method on the TBA api docs page. Let me know if you need anything else... v3 support coming soon
