### ISSUE TITLE
Update to 2017, and possibly keep 2016?

### ISSUE THREAD

**Issue by Techno11** [techguy9984/TBA-API#5]
If it is possible, (I know finals are coming up so don't fret it) could you update the API for Blue Alliance 2017 (When it's released, I can't seem to find any docs for it anywhere yet) but still keep all of the 2016 functionality?  I will link the documentation to it when I find it.

**Comment by widavies** [comment]
Sure

**Comment by Techno11** [comment]
Found this, I guess they are calling it the API v3 (Makes sense)

https://docs.google.com/document/d/19pej_DRaZdWUJKpsYRsM_pJDbB3TZA0CWRJRP7Qu978/edit#heading=h.wffkycnu1k1i

https://github.com/the-blue-alliance/the-blue-alliance/issues/1507

https://github.com/the-blue-alliance/the-blue-alliance/issues/1741

**Comment by widavies** [comment]
Yeah looks cool. As soon as v3 comes out I'll update the api to it

**Comment by Techno11** [comment]
Thanks

**Comment by widavies** [comment]
Yeah no problem

**Comment by Techno11** [comment]
It appears the v3 API is up, a lot of changes for the Teams and Events returns.  Waiting match breakdowns as referenced [here](https://github.com/the-blue-alliance/the-blue-alliance/issues/1741).

**Comment by widavies** [comment]
Alright awesome. I'm in the middle of finals right now so I'm guessing I'll
probably have the updated version done by Monday ish.

Are there any specific features you'd like added from the 2017 api?

**Comment by widavies** [comment]
Hi! So I've majorly updated the API. It now contains EVERY single method on the TBA api docs page. Phew. So I did quite a bit of research into the v3 api. Basically it just looks like they are adding the Simple Model, which returns a little less data, as well as changing a couple request methods. The V3 support for the API can be enabled with Settings.useV3(true). I'll be adding simple models probably today and working out the new request methods soon. Thanks for your patience! I hope you enjoy the new API. I don't think any of the others on the site have all the methods like mine does now - so I'm hoping that many people will find this API useful.
